### ISSUE TITLE
How to remove file from queue?

### ISSUE THREAD

**Issue by lonish** [jkuri/ngx-uploader#260]
Is there a possibility to remove files from queue?

**Comment by zorino** [comment]
+1

**Comment by be4code** [comment]
+1

**Comment by kayuda91** [comment]
+1

**Comment by jkuri** [comment]
fixed in `3.3.0`. there's a new input event `{ type: 'remove', id: file.id }`. https://github.com/jkuri/ngx-uploader/commit/d5758dd47386d42ea0cc0286e4ff826380d74fa8

**Comment by zorino** [comment]
OK now I have this error in 3.3.0 when trying to upload files 

TypeError: a.Observable.merge(...).mergeAll is not a function
    at ngx-uploader.umd.js:1

Also it doesn't seem to work since the file seem to stay in the queue.

**Comment by jkuri** [comment]
@zorino can you try with `3.3.1` and let me know please?

**Comment by zorino** [comment]
Yes it fixed the mergeAll function but the files are still not removed from queue..
For instance I add 3 files to the queue and remove one .. with the input event, the onUploadOutput will delete the file from the files array but when using the uploadAll input event afterward the 3 files are going to be uploaded.
